Repository FabLabsMC/fiber, pull requests merged in 2020-03, with the labels that each got.

#20 Add string constraints
  src/main/java/me/zeroeightsix/fiber/annotation/AnnotatedSettings.java
  src/main/java/me/zeroeightsix/fiber/annotation/Setting.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/AbstractConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/CompositeConstraintBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/ConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/constraint/Constraints.java
  src/main/java/me/zeroeightsix/fiber/constraint/RegexConstraint.java
  src/main/java/me/zeroeightsix/fiber/constraint/StringLengthConstraint.java
  src/test/java/me/zeroeightsix/fiber/annotation/AnnotatedSettingsTest.java
Labels: enhancement

#21 Implement aggregate constraints
  src/main/java/me/zeroeightsix/fiber/annotation/AnnotatedSettings.java
  src/main/java/me/zeroeightsix/fiber/annotation/Setting.java
  src/main/java/me/zeroeightsix/fiber/annotation/magic/TypeMagic.java
  src/main/java/me/zeroeightsix/fiber/builder/ConfigValueBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/AbstractConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/ComponentConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/CompositeConstraintBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/ConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/constraint/Constraints.java
  src/main/java/me/zeroeightsix/fiber/constraint/LengthConstraint.java
  src/main/java/me/zeroeightsix/fiber/constraint/StringLengthConstraint.java
  src/main/java/me/zeroeightsix/fiber/tree/ConfigValue.java
  src/test/java/me/zeroeightsix/fiber/JanksonSettingsTest.java
  src/test/java/me/zeroeightsix/fiber/annotation/AnnotatedSettingsTest.java
  src/test/java/me/zeroeightsix/fiber/builder/constraint/ConstraintsBuilderTest.java
Labels: enhancement, help wanted

#22 Add javadocs
  src/main/java/me/zeroeightsix/fiber/NodeOperations.java
  src/main/java/me/zeroeightsix/fiber/annotation/Listener.java
  src/main/java/me/zeroeightsix/fiber/annotation/Setting.java
  src/main/java/me/zeroeightsix/fiber/annotation/Settings.java
  src/main/java/me/zeroeightsix/fiber/annotation/convention/LowercaseConvention.java
  src/main/java/me/zeroeightsix/fiber/annotation/convention/NoNamingConvention.java
  src/main/java/me/zeroeightsix/fiber/annotation/convention/SettingNamingConvention.java
  src/main/java/me/zeroeightsix/fiber/annotation/convention/UnderscoredLowerCaseConvention.java
  src/main/java/me/zeroeightsix/fiber/annotation/exception/MalformedConstructorException.java
  src/main/java/me/zeroeightsix/fiber/annotation/exception/MalformedFieldException.java
  src/main/java/me/zeroeightsix/fiber/builder/ConfigValueBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/ComponentConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/CompositeConstraintBuilder.java
  src/main/java/me/zeroeightsix/fiber/builder/constraint/ConstraintsBuilder.java
  src/main/java/me/zeroeightsix/fiber/constraint/CompositeType.java
  src/main/java/me/zeroeightsix/fiber/constraint/Constraint.java
  src/main/java/me/zeroeightsix/fiber/constraint/ConstraintType.java
  src/main/java/me/zeroeightsix/fiber/constraint/LengthConstraint.java
  src/main/java/me/zeroeightsix/fiber/constraint/NumberConstraint.java
  src/main/java/me/zeroeightsix/fiber/constraint/RegexConstraint.java
  src/main/java/me/zeroeightsix/fiber/constraint/ValuedConstraint.java
  src/main/java/me/zeroeightsix/fiber/exception/FiberException.java
  src/main/java/me/zeroeightsix/fiber/exception/RuntimeFiberException.java
  src/main/java/me/zeroeightsix/fiber/tree/Commentable.java
  src/main/java/me/zeroeightsix/fiber/tree/ConfigLeaf.java
  src/main/java/me/zeroeightsix/fiber/tree/ConfigNode.java
  src/main/java/me/zeroeightsix/fiber/tree/ConfigValue.java
  src/main/java/me/zeroeightsix/fiber/tree/HasValue.java
  src/main/java/me/zeroeightsix/fiber/tree/Node.java
  src/main/java/me/zeroeightsix/fiber/tree/Property.java
  src/main/java/me/zeroeightsix/fiber/tree/Transparent.java
  src/main/java/me/zeroeightsix/fiber/tree/TreeItem.java
Labels: help wanted
