Repository FabLabsMC/fiber, pull requests merged in 2020-05, with the labels that each got.

#45 Add missing implementation for ConfigTreeBuilder#withMirroredValue
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/builder/ConfigTreeBuilder.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/tree/PropertyMirror.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/tree/ConfigBranchImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/tree/PropertyMirrorImpl.java
Labels: enhancement, refactor

#44 Improve enum types support
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/EnumSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/derived/ConfigTypes.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/AnnotatedSettingsImpl.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/AnnotatedSettingsTest.java
Labels: enhancement

#46 Update README
  README.md
Labels: refactor

#54 Split annotation processing into settings and processor
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/collect/ListenerProcessor.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/collect/MemberCollector.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/collect/SettingProcessor.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/AnnotatedSettingsImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/collect/MemberCollectorImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/collect/MemberCollectorRecursiveImpl.java
Labels: annotations, refactor

#53 Allow users to modify which fields of a class are processed by the annotation processor
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/AnnotatedSettings.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/collect/MemberCollector.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/collect/PojoMemberProcessor.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/exception/ProcessingMemberException.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/AnnotatedSettingsImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/collect/MemberCollectorImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/collect/MemberCollectorRecursiveImpl.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/AnnotatedSettingsTest.java
Labels: annotations, enhancement

#57 Builderify AnnotatedSettings
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/AnnotatedSettings.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/Listener.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/Setting.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/SettingNamingConvention.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/Settings.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/convention/LowercaseConvention.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/convention/NoNamingConvention.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/convention/SettingNamingConvention.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/convention/SnakeCaseConvention.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/convention/package-info.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/AnnotatedSettingsBuilderImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/AnnotatedSettingsImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/collect/MemberCollectorImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/collect/MemberCollectorRecursiveImpl.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/annotation/AnnotatedSettingsTest.java
  src/test/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/convention/NoNamingConventionTest.java
  src/test/java/io/github/fablabsmc/fablabs/impl/fiber/annotation/convention/SnakeCaseConventionTest.java
Labels: annotations, refactor

#52 Fix decimal increment comprehension check being too lenient
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/constraint/DecimalConstraintChecker.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/SerializableTypesTest.java
Labels: bug

#47 Make ConfigTreeBuilder#applyFromPojo throw an unchecked exception
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/builder/ConfigTreeBuilder.java
Labels: refactor

#59 Refactor Serializer -> ValueSerializer
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/exception/ValueDeserializationException.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/SchemaGenerator.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/BooleanSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/DecimalSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/EnumSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/ListSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/MapSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/ParameterizedSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/ParameterizedTypeImpl.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/PlainSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/RecordSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/SerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/StringSerializableType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/derived/ConfigType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/derived/RecordConfigType.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/JanksonSerializer.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/JanksonValueSerializer.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/Marshaller.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/Serializer.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/ValueSerializer.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/tree/ConfigAttribute.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/tree/ConfigLeaf.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/tree/HasValue.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/constraint/RecordConstraintChecker.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/serialization/FiberSerialization.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/tree/ConfigLeafImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/tree/ConfigNodeImpl.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/tree/PropertyMirrorImpl.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/JanksonSerializerTest.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/JanksonValueSerializerTest.java
Labels: refactor

#60 Remove automatic node sorting
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/schema/type/derived/ConfigTypes.java
  src/main/java/io/github/fablabsmc/fablabs/impl/fiber/tree/IndexedNodeCollection.java
Labels: bug
