Repository FabLabsMC/fiber, pull requests merged in 2020-06, with the labels that each got.

#67 Fix comments being removed during serialization
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/FiberSerialization.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/JanksonValueSerializer.java
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/ValueSerializer.java
  src/test/java/io/github/fablabsmc/fablabs/api/fiber/v1/serialization/JanksonValueSerializerTest.java
Labels: bug

#72 Fix invalid javadoc tags
  src/main/java/io/github/fablabsmc/fablabs/api/fiber/v1/builder/ConfigTreeBuilder.java
Labels: bug

#73 Create gradle.yml
  .github/workflows/gradle.yml
Labels: meta

#76 Fix maven publishing
  build.gradle.kts
Labels: bug, meta

#79 Bump version to 0.23.0
  gradle.properties
Labels: meta
